name: Claude Code Review
on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  id-token: write

jobs:
  claude-review:
    uses: oomol/workflows/.github/workflows/claude-code-review.yml@main
    secrets: inherit
